env:
  browser: true
  es2021: true
  mocha: true
extends:
  - standard-with-typescript
  - plugin:lit/recommended
  - plugin:lit-a11y/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules:
  '@typescript-eslint/no-non-null-assertion': off
